/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RevendeurRouteImport } from './routes/revendeur'
import { Route as SinophraRouteImport } from './routes/sinophra'
import { Route as RevendeurIndexRouteImport } from './routes/revendeur.index'
import { Route as RevendeurAnalyticsRouteImport } from './routes/revendeur.analytics'
import { Route as RevendeurCatalogueRouteImport } from './routes/revendeur.catalogue'
import { Route as RevendeurClientsRouteImport } from './routes/revendeur.clients'
import { Route as RevendeurCommandesRouteImport } from './routes/revendeur.commandes'
import { Route as RevendeurConfigurationRouteImport } from './routes/revendeur.configuration'
import { Route as RevendeurFacturesRouteImport } from './routes/revendeur.factures'
import { Route as RevendeurReclamationsRouteImport } from './routes/revendeur.reclamations'
import { Route as RevendeurUtilisateursRouteImport } from './routes/revendeur.utilisateurs'
import { Route as SinophraIndexRouteImport } from './routes/sinophra.index'
import { Route as SinophraAnalyticsRouteImport } from './routes/sinophra.analytics'
import { Route as SinophraApprovisionnementRouteImport } from './routes/sinophra.approvisionnement'
import { Route as SinophraCatalogueRouteImport } from './routes/sinophra.catalogue'
import { Route as SinophraCommandesRouteImport } from './routes/sinophra.commandes'
import { Route as SinophraConfigurationRouteImport } from './routes/sinophra.configuration'
import { Route as SinophraFacturationRouteImport } from './routes/sinophra.facturation'
import { Route as SinophraFournisseursRouteImport } from './routes/sinophra.fournisseurs'
import { Route as SinophraReclamationsRouteImport } from './routes/sinophra.reclamations'
import { Route as SinophraRevendeursRouteImport } from './routes/sinophra.revendeurs'
import { Route as SinophraUtilisateursRouteImport } from './routes/sinophra.utilisateurs'
import { Route as SinophraRevendeursIndexRouteImport } from './routes/sinophra.revendeurs.index'
import { Route as SinophraRevendeursIdRouteImport } from './routes/sinophra.revendeurs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevendeurRoute = RevendeurRouteImport.update({
  id: '/revendeur',
  path: '/revendeur',
  getParentRoute: () => rootRouteImport,
} as any)
const SinophraRoute = SinophraRouteImport.update({
  id: '/sinophra',
  path: '/sinophra',
  getParentRoute: () => rootRouteImport,
} as any)
const RevendeurIndexRoute = RevendeurIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RevendeurRoute,
} as any)
const RevendeurAnalyticsRoute = RevendeurAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => RevendeurRoute,
} as any)
const RevendeurCatalogueRoute = RevendeurCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => RevendeurRoute,
} as any)
const RevendeurClientsRoute = RevendeurClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => RevendeurRoute,
} as any)
const RevendeurCommandesRoute = RevendeurCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => RevendeurRoute,
} as any)
const RevendeurConfigurationRoute = RevendeurConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => RevendeurRoute,
} as any)
const RevendeurFacturesRoute = RevendeurFacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => RevendeurRoute,
} as any)
const RevendeurReclamationsRoute = RevendeurReclamationsRouteImport.update({
  id: '/reclamations',
  path: '/reclamations',
  getParentRoute: () => RevendeurRoute,
} as any)
const RevendeurUtilisateursRoute = RevendeurUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => RevendeurRoute,
} as any)
const SinophraIndexRoute = SinophraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SinophraRoute,
} as any)
const SinophraAnalyticsRoute = SinophraAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SinophraRoute,
} as any)
const SinophraApprovisionnementRoute =
  SinophraApprovisionnementRouteImport.update({
    id: '/approvisionnement',
    path: '/approvisionnement',
    getParentRoute: () => SinophraRoute,
  } as any)
const SinophraCatalogueRoute = SinophraCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => SinophraRoute,
} as any)
const SinophraCommandesRoute = SinophraCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => SinophraRoute,
} as any)
const SinophraConfigurationRoute = SinophraConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => SinophraRoute,
} as any)
const SinophraFacturationRoute = SinophraFacturationRouteImport.update({
  id: '/facturation',
  path: '/facturation',
  getParentRoute: () => SinophraRoute,
} as any)
const SinophraFournisseursRoute = SinophraFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => SinophraRoute,
} as any)
const SinophraReclamationsRoute = SinophraReclamationsRouteImport.update({
  id: '/reclamations',
  path: '/reclamations',
  getParentRoute: () => SinophraRoute,
} as any)
const SinophraRevendeursRoute = SinophraRevendeursRouteImport.update({
  id: '/revendeurs',
  path: '/revendeurs',
  getParentRoute: () => SinophraRoute,
} as any)
const SinophraUtilisateursRoute = SinophraUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => SinophraRoute,
} as any)
const SinophraRevendeursIndexRoute = SinophraRevendeursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SinophraRevendeursRoute,
} as any)
const SinophraRevendeursIdRoute = SinophraRevendeursIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SinophraRevendeursRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/revendeur': typeof RevendeurRouteWithChildren
  '/sinophra': typeof SinophraRouteWithChildren
  '/revendeur/analytics': typeof RevendeurAnalyticsRoute
  '/revendeur/catalogue': typeof RevendeurCatalogueRoute
  '/revendeur/clients': typeof RevendeurClientsRoute
  '/revendeur/commandes': typeof RevendeurCommandesRoute
  '/revendeur/configuration': typeof RevendeurConfigurationRoute
  '/revendeur/factures': typeof RevendeurFacturesRoute
  '/revendeur/reclamations': typeof RevendeurReclamationsRoute
  '/revendeur/utilisateurs': typeof RevendeurUtilisateursRoute
  '/sinophra/analytics': typeof SinophraAnalyticsRoute
  '/sinophra/approvisionnement': typeof SinophraApprovisionnementRoute
  '/sinophra/catalogue': typeof SinophraCatalogueRoute
  '/sinophra/commandes': typeof SinophraCommandesRoute
  '/sinophra/configuration': typeof SinophraConfigurationRoute
  '/sinophra/facturation': typeof SinophraFacturationRoute
  '/sinophra/fournisseurs': typeof SinophraFournisseursRoute
  '/sinophra/reclamations': typeof SinophraReclamationsRoute
  '/sinophra/revendeurs': typeof SinophraRevendeursRouteWithChildren
  '/sinophra/utilisateurs': typeof SinophraUtilisateursRoute
  '/revendeur/': typeof RevendeurIndexRoute
  '/sinophra/': typeof SinophraIndexRoute
  '/sinophra/revendeurs/$id': typeof SinophraRevendeursIdRoute
  '/sinophra/revendeurs/': typeof SinophraRevendeursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/revendeur/analytics': typeof RevendeurAnalyticsRoute
  '/revendeur/catalogue': typeof RevendeurCatalogueRoute
  '/revendeur/clients': typeof RevendeurClientsRoute
  '/revendeur/commandes': typeof RevendeurCommandesRoute
  '/revendeur/configuration': typeof RevendeurConfigurationRoute
  '/revendeur/factures': typeof RevendeurFacturesRoute
  '/revendeur/reclamations': typeof RevendeurReclamationsRoute
  '/revendeur/utilisateurs': typeof RevendeurUtilisateursRoute
  '/sinophra/analytics': typeof SinophraAnalyticsRoute
  '/sinophra/approvisionnement': typeof SinophraApprovisionnementRoute
  '/sinophra/catalogue': typeof SinophraCatalogueRoute
  '/sinophra/commandes': typeof SinophraCommandesRoute
  '/sinophra/configuration': typeof SinophraConfigurationRoute
  '/sinophra/facturation': typeof SinophraFacturationRoute
  '/sinophra/fournisseurs': typeof SinophraFournisseursRoute
  '/sinophra/reclamations': typeof SinophraReclamationsRoute
  '/sinophra/utilisateurs': typeof SinophraUtilisateursRoute
  '/revendeur': typeof RevendeurIndexRoute
  '/sinophra': typeof SinophraIndexRoute
  '/sinophra/revendeurs/$id': typeof SinophraRevendeursIdRoute
  '/sinophra/revendeurs': typeof SinophraRevendeursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/revendeur': typeof RevendeurRouteWithChildren
  '/sinophra': typeof SinophraRouteWithChildren
  '/revendeur/analytics': typeof RevendeurAnalyticsRoute
  '/revendeur/catalogue': typeof RevendeurCatalogueRoute
  '/revendeur/clients': typeof RevendeurClientsRoute
  '/revendeur/commandes': typeof RevendeurCommandesRoute
  '/revendeur/configuration': typeof RevendeurConfigurationRoute
  '/revendeur/factures': typeof RevendeurFacturesRoute
  '/revendeur/reclamations': typeof RevendeurReclamationsRoute
  '/revendeur/utilisateurs': typeof RevendeurUtilisateursRoute
  '/sinophra/analytics': typeof SinophraAnalyticsRoute
  '/sinophra/approvisionnement': typeof SinophraApprovisionnementRoute
  '/sinophra/catalogue': typeof SinophraCatalogueRoute
  '/sinophra/commandes': typeof SinophraCommandesRoute
  '/sinophra/configuration': typeof SinophraConfigurationRoute
  '/sinophra/facturation': typeof SinophraFacturationRoute
  '/sinophra/fournisseurs': typeof SinophraFournisseursRoute
  '/sinophra/reclamations': typeof SinophraReclamationsRoute
  '/sinophra/revendeurs': typeof SinophraRevendeursRouteWithChildren
  '/sinophra/utilisateurs': typeof SinophraUtilisateursRoute
  '/revendeur/': typeof RevendeurIndexRoute
  '/sinophra/': typeof SinophraIndexRoute
  '/sinophra/revendeurs/$id': typeof SinophraRevendeursIdRoute
  '/sinophra/revendeurs/': typeof SinophraRevendeursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/revendeur'
    | '/sinophra'
    | '/revendeur/analytics'
    | '/revendeur/catalogue'
    | '/revendeur/clients'
    | '/revendeur/commandes'
    | '/revendeur/configuration'
    | '/revendeur/factures'
    | '/revendeur/reclamations'
    | '/revendeur/utilisateurs'
    | '/sinophra/analytics'
    | '/sinophra/approvisionnement'
    | '/sinophra/catalogue'
    | '/sinophra/commandes'
    | '/sinophra/configuration'
    | '/sinophra/facturation'
    | '/sinophra/fournisseurs'
    | '/sinophra/reclamations'
    | '/sinophra/revendeurs'
    | '/sinophra/utilisateurs'
    | '/revendeur/'
    | '/sinophra/'
    | '/sinophra/revendeurs/$id'
    | '/sinophra/revendeurs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/revendeur/analytics'
    | '/revendeur/catalogue'
    | '/revendeur/clients'
    | '/revendeur/commandes'
    | '/revendeur/configuration'
    | '/revendeur/factures'
    | '/revendeur/reclamations'
    | '/revendeur/utilisateurs'
    | '/sinophra/analytics'
    | '/sinophra/approvisionnement'
    | '/sinophra/catalogue'
    | '/sinophra/commandes'
    | '/sinophra/configuration'
    | '/sinophra/facturation'
    | '/sinophra/fournisseurs'
    | '/sinophra/reclamations'
    | '/sinophra/utilisateurs'
    | '/revendeur'
    | '/sinophra'
    | '/sinophra/revendeurs/$id'
    | '/sinophra/revendeurs'
  id:
    | '__root__'
    | '/'
    | '/revendeur'
    | '/sinophra'
    | '/revendeur/analytics'
    | '/revendeur/catalogue'
    | '/revendeur/clients'
    | '/revendeur/commandes'
    | '/revendeur/configuration'
    | '/revendeur/factures'
    | '/revendeur/reclamations'
    | '/revendeur/utilisateurs'
    | '/sinophra/analytics'
    | '/sinophra/approvisionnement'
    | '/sinophra/catalogue'
    | '/sinophra/commandes'
    | '/sinophra/configuration'
    | '/sinophra/facturation'
    | '/sinophra/fournisseurs'
    | '/sinophra/reclamations'
    | '/sinophra/revendeurs'
    | '/sinophra/utilisateurs'
    | '/revendeur/'
    | '/sinophra/'
    | '/sinophra/revendeurs/$id'
    | '/sinophra/revendeurs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RevendeurRoute: typeof RevendeurRouteWithChildren
  SinophraRoute: typeof SinophraRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revendeur': {
      id: '/revendeur'
      path: '/revendeur'
      fullPath: '/revendeur'
      preLoaderRoute: typeof RevendeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinophra': {
      id: '/sinophra'
      path: '/sinophra'
      fullPath: '/sinophra'
      preLoaderRoute: typeof SinophraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revendeur/': {
      id: '/revendeur/'
      path: '/'
      fullPath: '/revendeur/'
      preLoaderRoute: typeof RevendeurIndexRouteImport
      parentRoute: typeof RevendeurRoute
    }
    '/revendeur/analytics': {
      id: '/revendeur/analytics'
      path: '/analytics'
      fullPath: '/revendeur/analytics'
      preLoaderRoute: typeof RevendeurAnalyticsRouteImport
      parentRoute: typeof RevendeurRoute
    }
    '/revendeur/catalogue': {
      id: '/revendeur/catalogue'
      path: '/catalogue'
      fullPath: '/revendeur/catalogue'
      preLoaderRoute: typeof RevendeurCatalogueRouteImport
      parentRoute: typeof RevendeurRoute
    }
    '/revendeur/clients': {
      id: '/revendeur/clients'
      path: '/clients'
      fullPath: '/revendeur/clients'
      preLoaderRoute: typeof RevendeurClientsRouteImport
      parentRoute: typeof RevendeurRoute
    }
    '/revendeur/commandes': {
      id: '/revendeur/commandes'
      path: '/commandes'
      fullPath: '/revendeur/commandes'
      preLoaderRoute: typeof RevendeurCommandesRouteImport
      parentRoute: typeof RevendeurRoute
    }
    '/revendeur/configuration': {
      id: '/revendeur/configuration'
      path: '/configuration'
      fullPath: '/revendeur/configuration'
      preLoaderRoute: typeof RevendeurConfigurationRouteImport
      parentRoute: typeof RevendeurRoute
    }
    '/revendeur/factures': {
      id: '/revendeur/factures'
      path: '/factures'
      fullPath: '/revendeur/factures'
      preLoaderRoute: typeof RevendeurFacturesRouteImport
      parentRoute: typeof RevendeurRoute
    }
    '/revendeur/reclamations': {
      id: '/revendeur/reclamations'
      path: '/reclamations'
      fullPath: '/revendeur/reclamations'
      preLoaderRoute: typeof RevendeurReclamationsRouteImport
      parentRoute: typeof RevendeurRoute
    }
    '/revendeur/utilisateurs': {
      id: '/revendeur/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/revendeur/utilisateurs'
      preLoaderRoute: typeof RevendeurUtilisateursRouteImport
      parentRoute: typeof RevendeurRoute
    }
    '/sinophra/': {
      id: '/sinophra/'
      path: '/'
      fullPath: '/sinophra/'
      preLoaderRoute: typeof SinophraIndexRouteImport
      parentRoute: typeof SinophraRoute
    }
    '/sinophra/analytics': {
      id: '/sinophra/analytics'
      path: '/analytics'
      fullPath: '/sinophra/analytics'
      preLoaderRoute: typeof SinophraAnalyticsRouteImport
      parentRoute: typeof SinophraRoute
    }
    '/sinophra/approvisionnement': {
      id: '/sinophra/approvisionnement'
      path: '/approvisionnement'
      fullPath: '/sinophra/approvisionnement'
      preLoaderRoute: typeof SinophraApprovisionnementRouteImport
      parentRoute: typeof SinophraRoute
    }
    '/sinophra/catalogue': {
      id: '/sinophra/catalogue'
      path: '/catalogue'
      fullPath: '/sinophra/catalogue'
      preLoaderRoute: typeof SinophraCatalogueRouteImport
      parentRoute: typeof SinophraRoute
    }
    '/sinophra/commandes': {
      id: '/sinophra/commandes'
      path: '/commandes'
      fullPath: '/sinophra/commandes'
      preLoaderRoute: typeof SinophraCommandesRouteImport
      parentRoute: typeof SinophraRoute
    }
    '/sinophra/configuration': {
      id: '/sinophra/configuration'
      path: '/configuration'
      fullPath: '/sinophra/configuration'
      preLoaderRoute: typeof SinophraConfigurationRouteImport
      parentRoute: typeof SinophraRoute
    }
    '/sinophra/facturation': {
      id: '/sinophra/facturation'
      path: '/facturation'
      fullPath: '/sinophra/facturation'
      preLoaderRoute: typeof SinophraFacturationRouteImport
      parentRoute: typeof SinophraRoute
    }
    '/sinophra/fournisseurs': {
      id: '/sinophra/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/sinophra/fournisseurs'
      preLoaderRoute: typeof SinophraFournisseursRouteImport
      parentRoute: typeof SinophraRoute
    }
    '/sinophra/reclamations': {
      id: '/sinophra/reclamations'
      path: '/reclamations'
      fullPath: '/sinophra/reclamations'
      preLoaderRoute: typeof SinophraReclamationsRouteImport
      parentRoute: typeof SinophraRoute
    }
    '/sinophra/revendeurs': {
      id: '/sinophra/revendeurs'
      path: '/revendeurs'
      fullPath: '/sinophra/revendeurs'
      preLoaderRoute: typeof SinophraRevendeursRouteImport
      parentRoute: typeof SinophraRoute
    }
    '/sinophra/utilisateurs': {
      id: '/sinophra/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/sinophra/utilisateurs'
      preLoaderRoute: typeof SinophraUtilisateursRouteImport
      parentRoute: typeof SinophraRoute
    }
    '/sinophra/revendeurs/': {
      id: '/sinophra/revendeurs/'
      path: '/'
      fullPath: '/sinophra/revendeurs/'
      preLoaderRoute: typeof SinophraRevendeursIndexRouteImport
      parentRoute: typeof SinophraRevendeursRoute
    }
    '/sinophra/revendeurs/$id': {
      id: '/sinophra/revendeurs/$id'
      path: '/$id'
      fullPath: '/sinophra/revendeurs/$id'
      preLoaderRoute: typeof SinophraRevendeursIdRouteImport
      parentRoute: typeof SinophraRevendeursRoute
    }
  }
}

interface RevendeurRouteChildren {
  RevendeurAnalyticsRoute: typeof RevendeurAnalyticsRoute
  RevendeurCatalogueRoute: typeof RevendeurCatalogueRoute
  RevendeurClientsRoute: typeof RevendeurClientsRoute
  RevendeurCommandesRoute: typeof RevendeurCommandesRoute
  RevendeurConfigurationRoute: typeof RevendeurConfigurationRoute
  RevendeurFacturesRoute: typeof RevendeurFacturesRoute
  RevendeurReclamationsRoute: typeof RevendeurReclamationsRoute
  RevendeurUtilisateursRoute: typeof RevendeurUtilisateursRoute
  RevendeurIndexRoute: typeof RevendeurIndexRoute
}

const RevendeurRouteChildren: RevendeurRouteChildren = {
  RevendeurAnalyticsRoute: RevendeurAnalyticsRoute,
  RevendeurCatalogueRoute: RevendeurCatalogueRoute,
  RevendeurClientsRoute: RevendeurClientsRoute,
  RevendeurCommandesRoute: RevendeurCommandesRoute,
  RevendeurConfigurationRoute: RevendeurConfigurationRoute,
  RevendeurFacturesRoute: RevendeurFacturesRoute,
  RevendeurReclamationsRoute: RevendeurReclamationsRoute,
  RevendeurUtilisateursRoute: RevendeurUtilisateursRoute,
  RevendeurIndexRoute: RevendeurIndexRoute,
}

const RevendeurRouteWithChildren = RevendeurRoute._addFileChildren(
  RevendeurRouteChildren,
)

interface SinophraRevendeursRouteChildren {
  SinophraRevendeursIdRoute: typeof SinophraRevendeursIdRoute
  SinophraRevendeursIndexRoute: typeof SinophraRevendeursIndexRoute
}

const SinophraRevendeursRouteChildren: SinophraRevendeursRouteChildren = {
  SinophraRevendeursIdRoute: SinophraRevendeursIdRoute,
  SinophraRevendeursIndexRoute: SinophraRevendeursIndexRoute,
}

const SinophraRevendeursRouteWithChildren =
  SinophraRevendeursRoute._addFileChildren(SinophraRevendeursRouteChildren)

interface SinophraRouteChildren {
  SinophraAnalyticsRoute: typeof SinophraAnalyticsRoute
  SinophraApprovisionnementRoute: typeof SinophraApprovisionnementRoute
  SinophraCatalogueRoute: typeof SinophraCatalogueRoute
  SinophraCommandesRoute: typeof SinophraCommandesRoute
  SinophraConfigurationRoute: typeof SinophraConfigurationRoute
  SinophraFacturationRoute: typeof SinophraFacturationRoute
  SinophraFournisseursRoute: typeof SinophraFournisseursRoute
  SinophraReclamationsRoute: typeof SinophraReclamationsRoute
  SinophraRevendeursRoute: typeof SinophraRevendeursRouteWithChildren
  SinophraUtilisateursRoute: typeof SinophraUtilisateursRoute
  SinophraIndexRoute: typeof SinophraIndexRoute
}

const SinophraRouteChildren: SinophraRouteChildren = {
  SinophraAnalyticsRoute: SinophraAnalyticsRoute,
  SinophraApprovisionnementRoute: SinophraApprovisionnementRoute,
  SinophraCatalogueRoute: SinophraCatalogueRoute,
  SinophraCommandesRoute: SinophraCommandesRoute,
  SinophraConfigurationRoute: SinophraConfigurationRoute,
  SinophraFacturationRoute: SinophraFacturationRoute,
  SinophraFournisseursRoute: SinophraFournisseursRoute,
  SinophraReclamationsRoute: SinophraReclamationsRoute,
  SinophraRevendeursRoute: SinophraRevendeursRouteWithChildren,
  SinophraUtilisateursRoute: SinophraUtilisateursRoute,
  SinophraIndexRoute: SinophraIndexRoute,
}

const SinophraRouteWithChildren = SinophraRoute._addFileChildren(
  SinophraRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RevendeurRoute: RevendeurRouteWithChildren,
  SinophraRoute: SinophraRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
